void *memcpy(void *dst,void *src,unsigned long int size)
{
	asm "push %rcx"
	asm "push %rdx"
	asm "push %rbx"
	asm "push %rsi"
	asm "push %rdi"
	asm "push %r8"
	asm "push %r9"
	asm "push %r10"
	asm "push %r11"
	asm "push %r12"
	asm "mov 16(%rbp),%rax"
	asm "mov 24(%rbp),%rdx"
	asm "mov 32(%rbp),%rcx"
	asm "cmp $8,%rcx"
	asm "jb @_memcpy_X33"
	asm "test $1,%dl"
	asm "je @_memcpy_X11"
	asm "mov (%rdx),%bl"
	asm "mov %bl,(%rax)"
	asm "inc %rax"
	asm "inc %rdx"
	asm "dec %rcx"
	asm "@_memcpy_X11"
	asm "test $2,%dl"
	asm "je @_memcpy_X12"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "add $2,%rax"
	asm "add $2,%rdx"
	asm "sub $2,%rcx"
	asm "@_memcpy_X12"
	asm "test $4,%dl"
	asm "je @_memcpy_X13"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "add $4,%rax"
	asm "add $4,%rdx"
	asm "sub $4,%rcx"
	asm "@_memcpy_X13"
	asm "sub $64,%rcx"
	asm "jb @_memcpy_X21"
	asm "@_memcpy_X22"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov 32(%rdx),%r9"
	asm "mov 40(%rdx),%r10"
	asm "mov 48(%rdx),%r11"
	asm "mov 56(%rdx),%r12"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "mov %r9,32(%rax)"
	asm "mov %r10,40(%rax)"
	asm "mov %r11,48(%rax)"
	asm "mov %r12,56(%rax)"
	asm "add $64,%rax"
	asm "add $64,%rdx"
	asm "sub $64,%rcx"
	asm "jae @_memcpy_X22"
	asm "@_memcpy_X21"
	asm "test $32,%cl"
	asm "je @_memcpy_X31"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "add $32,%rax"
	asm "add $32,%rdx"
	asm "@_memcpy_X31"
	asm "test $16,%cl"
	asm "je @_memcpy_X32"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "add $16,%rax"
	asm "add $16,%rdx"
	asm "@_memcpy_X32"
	asm "test $8,%cl"
	asm "je @_memcpy_X33"
	asm "mov (%rdx),%rbx"
	asm "mov %rbx,(%rax)"
	asm "add $8,%rax"
	asm "add $8,%rdx"
	asm "@_memcpy_X33"
	asm "test $4,%cl"
	asm "je @_memcpy_X34"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "add $4,%rax"
	asm "add $4,%rdx"
	asm "@_memcpy_X34"
	asm "test $2,%cl"
	asm "je @_memcpy_X35"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "add $2,%rax"
	asm "add $2,%rdx"
	asm "@_memcpy_X35"
	asm "test $1,%cl"
	asm "je @_memcpy_X36"
	asm "mov (%rdx),%bl"
	asm "mov %bl,(%rax)"
	asm "@_memcpy_X36"
	asm "pop %r12"
	asm "pop %r11"
	asm "pop %r10"
	asm "pop %r9"
	asm "pop %r8"
	asm "pop %rdi"
	asm "pop %rsi"
	asm "pop %rbx"
	asm "pop %rdx"
	asm "pop %rcx"
	asm "mov 16(%rbp),%rax"
}
void *memcpy_r(void *dst,void *src,unsigned long int size)
{
	asm "push %rcx"
	asm "push %rdx"
	asm "push %rbx"
	asm "push %rsi"
	asm "push %rdi"
	asm "push %r8"
	asm "push %r9"
	asm "push %r10"
	asm "push %r11"
	asm "push %r12"
	asm "mov 16(%rbp),%rax"
	asm "mov 24(%rbp),%rdx"
	asm "mov 32(%rbp),%rcx"
	asm "cmp $8,%rcx"
	asm "jb @_memcpy_r_X33"
	asm "test $1,%dl"
	asm "je @_memcpy_r_X11"
	asm "dec %rax"
	asm "dec %rdx"
	asm "dec %rcx"
	asm "mov (%rdx),%bl"
	asm "mov %bl,(%rax)"
	asm "@_memcpy_r_X11"
	asm "test $2,%dl"
	asm "je @_memcpy_r_X12"
	asm "sub $2,%rax"
	asm "sub $2,%rdx"
	asm "sub $2,%rcx"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "@_memcpy_r_X12"
	asm "test $4,%dl"
	asm "je @_memcpy_r_X13"
	asm "sub $4,%rax"
	asm "sub $4,%rdx"
	asm "sub $4,%rcx"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "@_memcpy_r_X13"
	asm "sub $64,%rcx"
	asm "jb @_memcpy_r_X21"
	asm "@_memcpy_r_X22"
	asm "sub $64,%rax"
	asm "sub $64,%rdx"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov 32(%rdx),%r9"
	asm "mov 40(%rdx),%r10"
	asm "mov 48(%rdx),%r11"
	asm "mov 56(%rdx),%r12"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "mov %r9,32(%rax)"
	asm "mov %r10,40(%rax)"
	asm "mov %r11,48(%rax)"
	asm "mov %r12,56(%rax)"
	asm "sub $64,%rcx"
	asm "jae @_memcpy_r_X22"
	asm "@_memcpy_r_X21"
	asm "test $32,%cl"
	asm "je @_memcpy_r_X31"
	asm "sub $32,%rax"
	asm "sub $32,%rdx"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "@_memcpy_r_X31"
	asm "test $16,%cl"
	asm "je @_memcpy_r_X32"
	asm "sub $16,%rax"
	asm "sub $16,%rdx"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "@_memcpy_r_X32"
	asm "test $8,%cl"
	asm "je @_memcpy_r_X33"
	asm "sub $8,%rax"
	asm "sub $8,%rdx"
	asm "mov (%rdx),%rbx"
	asm "mov %rbx,(%rax)"
	asm "@_memcpy_r_X33"
	asm "test $4,%cl"
	asm "je @_memcpy_r_X34"
	asm "sub $4,%rax"
	asm "sub $4,%rdx"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "@_memcpy_r_X34"
	asm "test $2,%cl"
	asm "je @_memcpy_r_X35"
	asm "sub $2,%rax"
	asm "sub $2,%rdx"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "@_memcpy_r_X35"
	asm "test $1,%cl"
	asm "je @_memcpy_r_X36"
	asm "mov -1(%rdx),%bl"
	asm "mov %bl,-1(%rax)"
	asm "@_memcpy_r_X36"
	asm "pop %r12"
	asm "pop %r11"
	asm "pop %r10"
	asm "pop %r9"
	asm "pop %r8"
	asm "pop %rdi"
	asm "pop %rsi"
	asm "pop %rbx"
	asm "pop %rdx"
	asm "pop %rcx"
	asm "mov 16(%rbp),%rax"
}
void *memmove(void *dst,void *src,unsigned long int size)
{
	if(dst<src||(char *)dst>=(char *)src+size)
	{
		return memcpy(dst,src,size);
	}
	else
	{
		memcpy_r((char *)dst+size,(char *)src+size,size);
		return dst;
	}
}
void *memset(void *mem,int val,unsigned long int size)
{
	asm "push %rcx"
	asm "push %rdx"
	asm "movzbl 24(%rbp),%edx"
	asm "mov $0x101010101010101,%rax"
	asm "mul %rdx"
	asm "mov %rax,%rdx"
	asm "mov 16(%rbp),%rax"
	asm "mov 32(%rbp),%rcx"
	asm "cmp $8,%rcx"
	asm "jb @_memset_X33"
	asm "test $1,%al"
	asm "je @_memset_X11"
	asm "mov %dl,(%rax)"
	asm "inc %rax"
	asm "dec %rcx"
	asm "@_memset_X11"
	asm "test $2,%al"
	asm "je @_memset_X12"
	asm "mov %dx,(%rax)"
	asm "add $2,%rax"
	asm "sub $2,%rcx"
	asm "@_memset_X12"
	asm "test $4,%al"
	asm "je @_memset_X13"
	asm "mov %edx,(%rax)"
	asm "add $4,%rax"
	asm "sub $4,%rcx"
	asm "@_memset_X13"
	asm "sub $64,%rcx"
	asm "jb @_memset_X21"
	asm "@_memset_X22"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "mov %rdx,16(%rax)"
	asm "mov %rdx,24(%rax)"
	asm "mov %rdx,32(%rax)"
	asm "mov %rdx,40(%rax)"
	asm "mov %rdx,48(%rax)"
	asm "mov %rdx,56(%rax)"
	asm "add $64,%rax"
	asm "sub $64,%rcx"
	asm "jae @_memset_X22"
	asm "@_memset_X21"
	asm "test $32,%cl"
	asm "je @_memset_X31"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "mov %rdx,16(%rax)"
	asm "mov %rdx,24(%rax)"
	asm "add $32,%rax"
	asm "@_memset_X31"
	asm "test $16,%cl"
	asm "je @_memset_X32"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "add $16,%rax"
	asm "@_memset_X32"
	asm "test $8,%cl"
	asm "je @_memset_X33"
	asm "mov %rdx,(%rax)"
	asm "add $8,%rax"
	asm "@_memset_X33"
	asm "test $4,%cl"
	asm "je @_memset_X34"
	asm "mov %edx,(%rax)"
	asm "add $4,%rax"
	asm "@_memset_X34"
	asm "test $2,%cl"
	asm "je @_memset_X35"
	asm "mov %dx,(%rax)"
	asm "add $2,%rax"
	asm "@_memset_X35"
	asm "test $1,%cl"
	asm "je @_memset_X36"
	asm "mov %dl,(%rax)"
	asm "@_memset_X36"
	asm "pop %rdx"
	asm "pop %rcx"
	asm "mov 16(%rbp),%rax"
}
int memcmp(void *mem1,void *mem2,unsigned long int size)
{
	asm "push %rsi"
	asm "push %rdi"
	asm "push %rcx"
	asm "mov 16(%rbp),%rsi"
	asm "mov 24(%rbp),%rdi"
	asm "mov 32(%rbp),%rcx"
	asm "sub $8,%rcx"
	asm "jb @_memcmp_X1"
	asm "@_memcmp_X2"
	asm "mov (%rsi),%rax"
	asm "sub (%rdi),%rax"
	asm "jne @_memcmp_E"
	asm "add $8,%rsi"
	asm "add $8,%rdi"
	asm "sub $8,%rcx"
	asm "jae @_memcmp_X2"
	asm "@_memcmp_X1"
	asm "test $4,%cl"
	asm "je @_memcmp_Y1"
	asm "mov (%rsi),%eax"
	asm "sub (%rdi),%eax"
	asm "jne @_memcmp_E"
	asm "add $4,%rsi"
	asm "add $4,%rdi"
	asm "@_memcmp_Y1"
	asm "test $2,%cl"
	asm "je @_memcmp_Y2"
	asm "mov (%rsi),%ax"
	asm "sub (%rdi),%ax"
	asm "jne @_memcmp_E"
	asm "add $2,%rsi"
	asm "add $2,%rdi"
	asm "@_memcmp_Y2"
	asm "test $1,%cl"
	asm "je @_memcmp_E2"
	asm "mov (%rsi),%al"
	asm "sub (%rdi),%al"
	asm "jne @_memcmp_E"
	asm "add $1,%rsi"
	asm "add $1,%rdi"
	asm "jmp @_memcmp_E2"
	asm "@_memcmp_E"
	asm "test %eax,%eax"
	asm "jne @_memcmp_E11"
	asm "shr $32,%rax"
	asm "@_memcmp_E11"
	asm "test %ax,%ax"
	asm "jne @_memcmp_E12"
	asm "shr $16,%rax"
	asm "@_memcmp_E12"
	asm "test %al,%al"
	asm "jne @_memcmp_E2"
	asm "mov %ah,%al"
	asm "@_memcmp_E2"
	asm "movsbq %al,%rax"
	asm "pop %rcx"
	asm "pop %rdi"
	asm "pop %rsi"
}
unsigned long int strlen(char *str)
{
	unsigned long int l;
	l=0;
	while(*str)
	{
		++l;
		++str;
	}
	return l;
}
unsigned long int strnlen(char *str,unsigned long int max)
{
	unsigned long int l;
	if(max==0)
	{
		return 0;
	}
	--max;
	l=0;
	while(*str&&l<max)
	{
		++l;
		++str;
	}
	return l;
}
int strcmp(char *str1,char *str2)
{
	unsigned long int l1,l2;
	l1=strlen(str1);
	l2=strlen(str2);
	if(l1>l2)
	{
		l1=l2;
	}
	return memcmp(str1,str2,l1+1);
}
int strncmp(char *str1,char *str2,unsigned long int max)
{
	unsigned long int l1,l2;
	l1=strnlen(str1,max);
	l2=strnlen(str2,max);
	if(l1>l2)
	{
		l1=l2;
	}
	return memcmp(str1,str2,l1+1);
}
char *strcpy(char *dst,char *src)
{
	unsigned long int l;
	l=strlen(src);
	memcpy(dst,src,l+1);
	return dst;
}
char *strcat(char *dst,char *src)
{
	unsigned long int l;
	l=strlen(dst);
	strcpy(dst+l,src);
	return dst;
}